<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:common="http://egov.bg/RegiX/MRRB"
           xmlns="http://egov.bg/RegiX/MRRB/ReportByAdmActRequest"
           targetNamespace="http://egov.bg/RegiX/MRRB/ReportByAdmActRequest"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
	<xs:import namespace="http://egov.bg/RegiX/MRRB" schemaLocation="../../MRRBCommon.xsd"/>
  <xs:element name="ReportByAdmActRequest" type="ReportByAdmActRequestType">
    <xs:annotation>
      <xs:documentation> Справка за издаден Административен акт</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="ReportByAdmActRequestType">
    <xs:annotation>
      <xs:documentation>Справка за издадени адмминистративни актове</xs:documentation>
    </xs:annotation>
    <xs:sequence>
		<xs:element name="RegNumber" type="xs:string" nillable="true"/>
		<xs:element name="RegDate" type="xs:date" nillable="true"/>
		<xs:element name="Administration" type="xs:string" nillable="true"/>
		<xs:element name="AdministrativeBody" type="common:AdministrativeBodyTypes" nillable="true"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
