// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.33667 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>Regix.MRRBAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Regix.MRRBAdapter
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ReportByAdmActRequestType
    {

        private string regNumberField;

        private System.Nullable<System.DateTime> regDateField;

        private string administrationField;

        private System.Nullable<AdministrativeBodyTypes> administrativeBodyField;

        public string RegNumber
        {
            get
            {
                return this.regNumberField;
            }
            set
            {
                this.regNumberField = value;
            }
        }

        public System.Nullable<System.DateTime> RegDate
        {
            get
            {
                return this.regDateField;
            }
            set
            {
                this.regDateField = value;
            }
        }

        public string Administration
        {
            get
            {
                return this.administrationField;
            }
            set
            {
                this.administrationField = value;
            }
        }

        public System.Nullable<AdministrativeBodyTypes> AdministrativeBody
        {
            get
            {
                return this.administrativeBodyField;
            }
            set
            {
                this.administrativeBodyField = value;
            }
        }
    }

    public enum AdministrativeBodyTypes
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230ff0dd-8d2d-46f5-a04b-36bc4557bf0f")]
        Item230ff0dd8d2d46f5a04b36bc4557bf0f,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("a861c8a7-a3b4-4c63-bbb9-c75479c82973")]
        a861c8a7a3b44c63bbb9c75479c82973,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("bc77f8ab-031e-4322-9fd9-617f777afd76")]
        bc77f8ab031e43229fd9617f777afd76,
    }
}
