// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.33667 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>Regix.MRRBAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Integration.MRRBAdapter
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class AdmActInfoResponseType
    {

        private NomenclatureType errorField;

        private List<AmdActResponseType> amdActResponseField;

        public AdmActInfoResponseType()
        {
            this.amdActResponseField = new List<AmdActResponseType>();
            this.errorField = new NomenclatureType();
        }

        public NomenclatureType Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        public List<AmdActResponseType> AmdActResponse
        {
            get
            {
                return this.amdActResponseField;
            }
            set
            {
                this.amdActResponseField = value;
            }
        }
    }

    public partial class NomenclatureType
    {

        private string codeField;

        private string nameField;

        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class ActObjectType
    {

        private NomenclatureType provinceField;

        private NomenclatureType municipalityField;

        private NomenclatureType settlementField;

        private NomenclatureType regionField;

        private string cadIdentifierField;

        private string regPlaceField;

        private string regQuarterField;

        private string regUpiField;

        private string cadPlanRegionField;

        private string cadPlanNumberField;

        public ActObjectType()
        {
            this.regionField = new NomenclatureType();
            this.settlementField = new NomenclatureType();
            this.municipalityField = new NomenclatureType();
            this.provinceField = new NomenclatureType();
        }

        public NomenclatureType Province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }

        public NomenclatureType Municipality
        {
            get
            {
                return this.municipalityField;
            }
            set
            {
                this.municipalityField = value;
            }
        }

        public NomenclatureType Settlement
        {
            get
            {
                return this.settlementField;
            }
            set
            {
                this.settlementField = value;
            }
        }

        public NomenclatureType Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        public string CadIdentifier
        {
            get
            {
                return this.cadIdentifierField;
            }
            set
            {
                this.cadIdentifierField = value;
            }
        }

        public string RegPlace
        {
            get
            {
                return this.regPlaceField;
            }
            set
            {
                this.regPlaceField = value;
            }
        }

        public string RegQuarter
        {
            get
            {
                return this.regQuarterField;
            }
            set
            {
                this.regQuarterField = value;
            }
        }

        public string RegUpi
        {
            get
            {
                return this.regUpiField;
            }
            set
            {
                this.regUpiField = value;
            }
        }

        public string CadPlanRegion
        {
            get
            {
                return this.cadPlanRegionField;
            }
            set
            {
                this.cadPlanRegionField = value;
            }
        }

        public string CadPlanNumber
        {
            get
            {
                return this.cadPlanNumberField;
            }
            set
            {
                this.cadPlanNumberField = value;
            }
        }
    }

    public partial class AdmActObjectType
    {

        private string nameDescField;

        private List<ActObjectType> actObjectField;

        public AdmActObjectType()
        {
            this.actObjectField = new List<ActObjectType>();
        }

        public string NameDesc
        {
            get
            {
                return this.nameDescField;
            }
            set
            {
                this.nameDescField = value;
            }
        }

        public List<ActObjectType> ActObject
        {
            get
            {
                return this.actObjectField;
            }
            set
            {
                this.actObjectField = value;
            }
        }
    }

    public partial class IssuerType
    {

        private string administrationField;

        private NomenclatureType administrativeBodyField;

        public IssuerType()
        {
            this.administrativeBodyField = new NomenclatureType();
        }

        public string Administration
        {
            get
            {
                return this.administrationField;
            }
            set
            {
                this.administrationField = value;
            }
        }

        public NomenclatureType AdministrativeBody
        {
            get
            {
                return this.administrativeBodyField;
            }
            set
            {
                this.administrativeBodyField = value;
            }
        }
    }

    public partial class Applicant
    {

        private string fullNameField;

        private string egnBulstatField;

        private string addressField;

        private string typeField;

        private string qualityNameField;

        private string phoneField;

        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        public string EgnBulstat
        {
            get
            {
                return this.egnBulstatField;
            }
            set
            {
                this.egnBulstatField = value;
            }
        }

        public string Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public string QualityName
        {
            get
            {
                return this.qualityNameField;
            }
            set
            {
                this.qualityNameField = value;
            }
        }

        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }

    public partial class AdmActType
    {

        private string regNumberField;

        private string regDateField;

        private string annoucmentDateField;

        private NomenclatureType annoucmentTypeField;

        private string effectiveDateField;

        private NomenclatureType typeField;

        private NomenclatureType stateField;

        private string validByDateField;

        public AdmActType()
        {
            this.stateField = new NomenclatureType();
            this.typeField = new NomenclatureType();
            this.annoucmentTypeField = new NomenclatureType();
        }

        public string RegNumber
        {
            get
            {
                return this.regNumberField;
            }
            set
            {
                this.regNumberField = value;
            }
        }

        public string RegDate
        {
            get
            {
                return this.regDateField;
            }
            set
            {
                this.regDateField = value;
            }
        }

        public string AnnoucmentDate
        {
            get
            {
                return this.annoucmentDateField;
            }
            set
            {
                this.annoucmentDateField = value;
            }
        }

        public NomenclatureType AnnoucmentType
        {
            get
            {
                return this.annoucmentTypeField;
            }
            set
            {
                this.annoucmentTypeField = value;
            }
        }

        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }

        public NomenclatureType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public NomenclatureType State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        public string ValidByDate
        {
            get
            {
                return this.validByDateField;
            }
            set
            {
                this.validByDateField = value;
            }
        }
    }

    public partial class AmdActResponseType
    {

        private AdmActType admActField;

        private List<Applicant> applicantField;

        private IssuerType issuerField;

        private AdmActObjectType admActObjectField;

        public AmdActResponseType()
        {
            this.admActObjectField = new AdmActObjectType();
            this.issuerField = new IssuerType();
            this.applicantField = new List<Applicant>();
            this.admActField = new AdmActType();
        }

        public AdmActType AdmAct
        {
            get
            {
                return this.admActField;
            }
            set
            {
                this.admActField = value;
            }
        }

        public List<Applicant> Applicant
        {
            get
            {
                return this.applicantField;
            }
            set
            {
                this.applicantField = value;
            }
        }

        public IssuerType Issuer
        {
            get
            {
                return this.issuerField;
            }
            set
            {
                this.issuerField = value;
            }
        }

        public AdmActObjectType AdmActObject
        {
            get
            {
                return this.admActObjectField;
            }
            set
            {
                this.admActObjectField = value;
            }
        }
    }
}
