<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:common="http://egov.bg/RegiX/MRRB"
           xmlns="http://egov.bg/RegiX/MRRB/ReportyByUICRquest"
           targetNamespace="http://egov.bg/RegiX/MRRB/ReportyByUICRquest"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
  <xs:import namespace="http://egov.bg/RegiX/MRRB" schemaLocation="../../MRRBCommon.xsd"/>
  <xs:element name="ReportByCadNumberRequest" type="ReportByUICRequestType">
    <xs:annotation>
      <xs:documentation>ЕИК (категория Заявител)</xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="ReportByUICRequestType">
    <xs:annotation>
      <xs:documentation>Справка за издадени адмминистративни актове</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="UIC" type="common:UIC" nillable="false" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>
