<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Configurations>Debug;Release;</Configurations>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
    <SatelliteResourceLanguages>en-US;bg-BG</SatelliteResourceLanguages>
    <CodeAnalysisRuleSet>..\..\Rules.ruleset</CodeAnalysisRuleSet>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>CS8600;CS8602;CS8603</WarningsAsErrors>
    <NoWarn>NU1608;NU1803</NoWarn>
    <Version></Version>
	<NuGetAudit>false</NuGetAudit>
	<AssemblyVersion>3.1.28</AssemblyVersion>
  </PropertyGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<Content Include="..\Kendo.Mvc\bin\Release\net8.0\bg-BG\Kendo.Mvc.resources.dll" Link="bg-BG\Kendo.Mvc.resources.dll" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="..\..\stylecop.json" />
		<Content Include="App_Data\**" CopyToPublishDirectory="Always" />
		<Compile Remove="BISS\**" />
		<Compile Remove="Scripts\Controllers\OutAdmAct\**" />
		<Compile Remove="Views\OutAdmAct\**" />
		<TypeScriptCompile Remove="BISS\**" />
		<TypeScriptCompile Remove="node_modules\**" />
		<TypeScriptCompile Remove="Scripts\Controllers\OutAdmAct\**" />
		<TypeScriptCompile Remove="Views\OutAdmAct\**" />
		<Content Remove="BISS\**" />
		<Content Remove="Scripts\Controllers\OutAdmAct\**" />
		<Content Remove="Views\OutAdmAct\**" />
		<Content Remove="wwwroot\scripts\**" />
		<EmbeddedResource Remove="BISS\**" />
		<EmbeddedResource Remove="Scripts\Controllers\OutAdmAct\**" />
		<EmbeddedResource Remove="Views\OutAdmAct\**" />
		<None Remove="BISS\**" />
		<None Remove="Scripts\Controllers\OutAdmAct\**" />
		<None Remove="Views\OutAdmAct\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="Controllers\OutAdmActController.cs" />
	</ItemGroup>

	<ItemGroup>
	  <_WebToolingArtifacts Remove="properties\publishprofiles\MapexMrrbInternal.pubxml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Ais.Payments" Version="2.0.1" />
		<PackageReference Include="Ais.Regix.Net.Core" Version="1.0.4" />
		<PackageReference Include="AspNet.Security.OAuth.ArcGIS" Version="8.1.0" />
		<PackageReference Include="AutoMapper" Version="13.0.1" />
		<PackageReference Include="EasyCaching.Redis" Version="1.9.2" />
		<PackageReference Include="EasyCaching.Serialization.SystemTextJson" Version="1.9.2" />
		<PackageReference Include="Elasticsearch.Net" Version="7.17.4" />
		<PackageReference Include="Google.Protobuf.Tools" Version="3.31.0" />
		<PackageReference Include="Grpc.AspNetCore.Server.ClientFactory" Version="2.65.0" />
		<PackageReference Include="IO.SignTools" Version="6.0.11" />
		<PackageReference Include="ITfoxtec.Identity.Saml2.MvcCore" Version="4.13.2" />
		<PackageReference Include="MessagePack" Version="2.5.108" />
		<PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="8.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.7" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.7" />
		<PackageReference Include="Microsoft.TypeScript.MSBuild" Version="5.5.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NEST" Version="7.17.4" />
		<PackageReference Include="OpenXmlTemplateEngine" Version="1.2.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="8.0.2" />
		<PackageReference Include="Serilog.Enrichers.ClientInfo" Version="2.1.2" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.Http" Version="9.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.7" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.8" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.10.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.10.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
		<PackageReference Include="Telerik.Documents.ImageUtils" Version="2024.2.426" />
		<PackageReference Include="Telerik.Documents.SpreadsheetStreaming" Version="2024.2.426" />
		<PackageReference Include="Telerik.UI.for.AspNet.Core" Version="2024.2.514" />
		<PackageReference Include="Telerik.Web.PDF" Version="2024.2.514" />
		<PackageReference Include="Telerik.WebReportDesigner.Services" Version="18.1.24.709" />
		<PackageReference Include="Gapotchenko.Eazfuscator.NET" Version="2024.2.614">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="App_Data\Templates\Email\" />
		<Folder Include="App_Data\Templates\Excel\" />
		<Folder Include="App_Data\Templates\Pdf\" />
		<Folder Include="Areas\Reports\Scripts\" />
		<Folder Include="Properties\PublishProfiles\" />
		<Folder Include="wwwroot\TempPdf\" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Ais.Common">
		  <HintPath>..\..\Libs\Ais.Common.dll</HintPath>
		</Reference>
		<Reference Include="Ais.Data.Common">
			<HintPath>..\..\Libs\Ais.Data.Common.dll</HintPath>
		</Reference>
	  <Reference Include="Ais.Data">
	    <HintPath>..\..\Libs\Ais.Data.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Data.Models">
	    <HintPath>..\..\Libs\Ais.Data.Models.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.GrpcContracts">
	    <HintPath>..\..\Libs\Ais.GrpcContracts.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Infrastructure">
	    <HintPath>..\..\Libs\Ais.Infrastructure.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Office.ViewModels">
	    <HintPath>..\..\Libs\Ais.Office.ViewModels.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Portal.ViewModels">
	    <HintPath>..\..\Libs\Ais.Portal.ViewModels.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Resources">
	    <HintPath>..\..\Libs\Ais.Resources.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Services">
	    <HintPath>..\..\Libs\Ais.Services.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Services.Data">
	    <HintPath>..\..\Libs\Ais.Services.Data.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Services.Mapping">
	    <HintPath>..\..\Libs\Ais.Services.Mapping.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Table.Mvc">
	    <HintPath>..\..\Libs\Ais.Table.Mvc.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.Utilities">
	    <HintPath>..\..\Libs\Ais.Utilities.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.WebServices">
	    <HintPath>..\..\Libs\Ais.WebServices.dll</HintPath>
	  </Reference>
	  <Reference Include="Ais.WebUtilities">
	    <HintPath>..\..\Libs\Ais.WebUtilities.dll</HintPath>
	  </Reference>
	  <Reference Include="Kendo.Mvc">
	    <HintPath>..\..\Libs\Kendo.Mvc.dll</HintPath>
	  </Reference>
	</ItemGroup>
  
	<ItemGroup>
	  <Content Update="Areas\OutAdministrativeAct\Views\OutApplication\Info\_Index.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>
</Project>
